# build stage
FROM node:24-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# runtime stage
FROM nginx:alpine
COPY --from=build /app/dist/web/browser /usr/share/nginx/html

EXPOSE 80